Microsoft Windows [Version 10.0.22631.3447]
(c) Microsoft Corporation. All rights reserved.

C:\Users\VIGNEZ>cd AppData\Local\Python\Python312\Scripts

C:\Users\VIGNEZ\AppData\Local\Python\Python312\Scripts>cd..

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install flask
Collecting flask
  Downloading flask-3.0.3-py3-none-any.whl.metadata (3.2 kB)
Collecting Werkzeug>=3.0.0 (from flask)
  Downloading werkzeug-3.0.2-py3-none-any.whl.metadata (4.1 kB)
Collecting Jinja2>=3.1.2 (from flask)
  Downloading Jinja2-3.1.3-py3-none-any.whl.metadata (3.3 kB)
Collecting itsdangerous>=2.1.2 (from flask)
  Downloading itsdangerous-2.2.0-py3-none-any.whl.metadata (1.9 kB)
Collecting click>=8.1.3 (from flask)
  Downloading click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting blinker>=1.6.2 (from flask)
  Downloading blinker-1.8.0-py3-none-any.whl.metadata (1.6 kB)
Collecting colorama (from click>=8.1.3->flask)
  Downloading colorama-0.4.6-py2.py3-none-any.whl.metadata (17 kB)
Collecting MarkupSafe>=2.0 (from Jinja2>=3.1.2->flask)
  Downloading MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Downloading flask-3.0.3-py3-none-any.whl (101 kB)
   ---------------------------------------- 101.7/101.7 kB 124.5 kB/s eta 0:00:00
Downloading blinker-1.8.0-py3-none-any.whl (9.3 kB)
Downloading click-8.1.7-py3-none-any.whl (97 kB)
   ---------------------------------------- 97.9/97.9 kB 193.6 kB/s eta 0:00:00
Downloading itsdangerous-2.2.0-py3-none-any.whl (16 kB)
Downloading Jinja2-3.1.3-py3-none-any.whl (133 kB)
   ---------------------------------------- 133.2/133.2 kB 97.2 kB/s eta 0:00:00
Downloading werkzeug-3.0.2-py3-none-any.whl (226 kB)
   ---------------------------------------- 226.8/226.8 kB 105.0 kB/s eta 0:00:00
Downloading MarkupSafe-2.1.5-cp312-cp312-win_amd64.whl (17 kB)
Downloading colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Installing collected packages: MarkupSafe, itsdangerous, colorama, blinker, Werkzeug, Jinja2, click, flask
Successfully installed Jinja2-3.1.3 MarkupSafe-2.1.5 Werkzeug-3.0.2 blinker-1.8.0 click-8.1.7 colorama-0.4.6 flask-3.0.3 itsdangerous-2.2.0

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install bcrypt
Collecting bcrypt
  Downloading bcrypt-4.1.2-cp39-abi3-win_amd64.whl.metadata (9.8 kB)
Downloading bcrypt-4.1.2-cp39-abi3-win_amd64.whl (158 kB)
   ---------------------------------------- 158.3/158.3 kB 86.9 kB/s eta 0:00:00
Installing collected packages: bcrypt
Successfully installed bcrypt-4.1.2

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install json
ERROR: Could not find a version that satisfies the requirement json (from versions: none)
ERROR: No matching distribution found for json

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install os
ERROR: Could not find a version that satisfies the requirement os (from versions: none)
ERROR: No matching distribution found for os

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install mysql
Collecting mysql
  Downloading mysql-0.0.3-py3-none-any.whl.metadata (746 bytes)
Collecting mysqlclient (from mysql)
  Downloading mysqlclient-2.2.4-cp312-cp312-win_amd64.whl.metadata (4.6 kB)
Downloading mysql-0.0.3-py3-none-any.whl (1.2 kB)
Downloading mysqlclient-2.2.4-cp312-cp312-win_amd64.whl (203 kB)
   ---------------------------------------- 203.3/203.3 kB 179.1 kB/s eta 0:00:00
Installing collected packages: mysqlclient, mysql
Successfully installed mysql-0.0.3 mysqlclient-2.2.4

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install request
ERROR: Could not find a version that satisfies the requirement request (from versions: none)
ERROR: No matching distribution found for request

C:\Users\VIGNEZ\AppData\Local\Python\Python312>cd../../../../

C:\Users\VIGNEZ>cd..

C:\Users>d:

D:\>cd project

D:\project>python app.py
Traceback (most recent call last):
  File "D:\project\app.py", line 2, in <module>
    import requests  # Import the requests library for making HTTP requests
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'requests'

D:\project>cd AppData\Local\Python\Python312\Scripts
The system cannot find the path specified.

D:\project>c:

C:\Users>cd vignez

C:\Users\VIGNEZ>cd AppData\Local\Python\Python312\Scripts

C:\Users\VIGNEZ\AppData\Local\Python\Python312\Scripts>cd..

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install requests
Collecting requests
  Downloading requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting charset-normalizer<4,>=2 (from requests)
  Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl.metadata (34 kB)
Collecting idna<4,>=2.5 (from requests)
  Downloading idna-3.7-py3-none-any.whl.metadata (9.9 kB)
Collecting urllib3<3,>=1.21.1 (from requests)
  Downloading urllib3-2.2.1-py3-none-any.whl.metadata (6.4 kB)
Collecting certifi>=2017.4.17 (from requests)
  Downloading certifi-2024.2.2-py3-none-any.whl.metadata (2.2 kB)
Downloading requests-2.31.0-py3-none-any.whl (62 kB)
   ---------------------------------------- 62.6/62.6 kB 134.2 kB/s eta 0:00:00
Downloading certifi-2024.2.2-py3-none-any.whl (163 kB)
   ---------------------------------------- 163.8/163.8 kB 106.8 kB/s eta 0:00:00
Downloading charset_normalizer-3.3.2-cp312-cp312-win_amd64.whl (100 kB)
   ---------------------------------------- 100.4/100.4 kB 108.9 kB/s eta 0:00:00
Downloading idna-3.7-py3-none-any.whl (66 kB)
   ---------------------------------------- 66.8/66.8 kB 124.9 kB/s eta 0:00:00
Downloading urllib3-2.2.1-py3-none-any.whl (121 kB)
   ---------------------------------------- 121.1/121.1 kB 139.1 kB/s eta 0:00:00
Installing collected packages: urllib3, idna, charset-normalizer, certifi, requests
Successfully installed certifi-2024.2.2 charset-normalizer-3.3.2 idna-3.7 requests-2.31.0 urllib3-2.2.1

C:\Users\VIGNEZ\AppData\Local\Python\Python312>d:

D:\project>python app.py
Traceback (most recent call last):
  File "D:\project\app.py", line 4, in <module>
    from flask_mysqldb import MySQL
ModuleNotFoundError: No module named 'flask_mysqldb'

D:\project>c:

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install requestspip install flask-mysqldb
ERROR: Could not find a version that satisfies the requirement requestspip (from versions: none)
ERROR: No matching distribution found for requestspip

C:\Users\VIGNEZ\AppData\Local\Python\Python312>python.exe -m pip install flask-mysqldb
Collecting flask-mysqldb
  Using cached Flask_MySQLdb-2.0.0-py3-none-any.whl.metadata (3.0 kB)
Requirement already satisfied: Flask>=1.0.4 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from flask-mysqldb) (3.0.3)
Requirement already satisfied: mysqlclient>=2.2.0 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from flask-mysqldb) (2.2.4)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from Flask>=1.0.4->flask-mysqldb) (3.0.2)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from Flask>=1.0.4->flask-mysqldb) (3.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from Flask>=1.0.4->flask-mysqldb) (2.2.0)
Requirement already satisfied: click>=8.1.3 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from Flask>=1.0.4->flask-mysqldb) (8.1.7)
Requirement already satisfied: blinker>=1.6.2 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from Flask>=1.0.4->flask-mysqldb) (1.8.0)
Requirement already satisfied: colorama in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from click>=8.1.3->Flask>=1.0.4->flask-mysqldb) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\vignez\appdata\local\python\python312\lib\site-packages (from Jinja2>=3.1.2->Flask>=1.0.4->flask-mysqldb) (2.1.5)
Using cached Flask_MySQLdb-2.0.0-py3-none-any.whl (4.9 kB)
Installing collected packages: flask-mysqldb
Successfully installed flask-mysqldb-2.0.0

C:\Users\VIGNEZ\AppData\Local\Python\Python312>d:

D:\project>python app.py
 * Serving Flask app 'app'
 * Debug mode: on
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:3000
Press CTRL+C to quit
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 551-163-118
127.0.0.1 - - [28/Apr/2024 16:21:58] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:21:59] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [28/Apr/2024 16:22:08] "GET /signup HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:22:29] "POST /signup HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\app.py", line 39, in signup
    cursor = mysql.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 109, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 97, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
127.0.0.1 - - [28/Apr/2024 16:22:29] "GET /signup?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:22:29] "GET /signup?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:22:29] "GET /signup?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:22:29] "GET /signup?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:24:48] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:24:50] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:25:10] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\app.py", line 67, in login
    cursor = mysql.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 109, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 97, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
127.0.0.1 - - [28/Apr/2024 16:25:10] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:25:10] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:25:10] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:25:11] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:51:13] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:51:25] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:51:46] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\app.py", line 67, in login
    cursor = mysql.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 109, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 97, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1045, "Access denied for user 'root'@'localhost' (using password: NO)")
127.0.0.1 - - [28/Apr/2024 16:51:46] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:51:46] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:51:46] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:51:46] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
 * Detected change in 'D:\\project\\app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 551-163-118
127.0.0.1 - - [28/Apr/2024 16:55:09] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:55:11] "GET /login HTTP/1.1" 200 -
127.0.0.1 - - [28/Apr/2024 16:55:23] "POST /login HTTP/1.1" 500 -
Traceback (most recent call last):
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1498, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1476, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\project\app.py", line 67, in login
    cursor = mysql.connection.cursor()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 109, in connection
    ctx.mysql_db = self.connect
                   ^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\flask_mysqldb\__init__.py", line 97, in connect
    return MySQLdb.connect(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\VIGNEZ\AppData\Local\Python\Python312\Lib\site-packages\MySQLdb\connections.py", line 195, in __init__
    super().__init__(*args, **kwargs2)
MySQLdb.OperationalError: (1049, "Unknown database 'legal_assistant'")
127.0.0.1 - - [28/Apr/2024 16:55:23] "GET /login?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:55:23] "GET /login?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:55:23] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
127.0.0.1 - - [28/Apr/2024 16:55:23] "GET /login?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 304 -
